"""
KimiGPT - Deployment Agent
"""

import logging
from typing import Dict, Any
import os
import zipfile
from io import BytesIO
from datetime import datetime

logger = logging.getLogger(__name__)


class DeploymentAgent:
    """Deployment Agent - packages and prepares websites for deployment"""

    def __init__(self, api_manager):
        self.api_manager = api_manager

    def package_website(self, analysis: Dict[str, Any],
                       task_5_output: Dict = None,
                       task_6_output: Dict = None,
                       **kwargs) -> Dict[str, Any]:
        """Package website into deployable format"""
        logger.info("Deployment Agent: Packaging website...")

        files = task_5_output.get("files", {}) if task_5_output else {}
        qa_results = task_6_output or {}

        # Generate project name
        website_type = analysis.get("website_type", "website")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        project_name = f"{website_type}_{timestamp}"

        # Create file structure
        file_structure = self._organize_files(files)

        # Add README
        file_structure["README.md"] = self._generate_readme(analysis, qa_results)

        # Add deployment guide
        file_structure["DEPLOYMENT.md"] = self._generate_deployment_guide()

        # Create ZIP package
        zip_path = self._create_zip(project_name, file_structure)

        result = {
            "project_name": project_name,
            "files": file_structure,
            "zip_path": zip_path,
            "deployment_options": self._get_deployment_options(),
            "qa_score": qa_results.get("overall_score", 0)
        }

        logger.info(f"✓ Website packaged successfully: {project_name}")

        return result

    def _organize_files(self, files: Dict[str, str]) -> Dict[str, str]:
        """Organize files into proper structure"""
        organized = {}

        for file_path, content in files.items():
            organized[file_path] = content

        # Add additional files
        organized["css/responsive.css"] = ""  # Placeholder
        organized["images/.gitkeep"] = ""
        organized["js/utils.js"] = ""  # Placeholder

        return organized

    def _generate_readme(self, analysis: Dict, qa_results: Dict) -> str:
        """Generate README.md"""
        website_type = analysis.get("website_type", "Website")
        score = qa_results.get("overall_score", 0)

        return f"""# {website_type.title()} Website

## 🎨 Generated by KimiGPT

This professional {website_type} website was generated using KimiGPT's multi-agent AI system.

### 📊 Quality Score: {score:.1f}/100

### ✨ Features
- Fully responsive design (mobile, tablet, desktop)
- Modern, clean aesthetics
- SEO optimized
- Accessibility compliant (WCAG AA)
- Cross-browser compatible
- Fast loading performance

### 🚀 Quick Start

1. Extract the ZIP file
2. Open `index.html` in your browser
3. Customize content as needed

### 📁 File Structure
```
/
├── index.html          # Main HTML file
├── css/
│   └── styles.css     # Stylesheet
├── js/
│   └── main.js        # JavaScript
├── images/            # Image assets
└── README.md          # This file
```

### 🌐 Deployment

See `DEPLOYMENT.md` for deployment instructions.

### 📝 Customization

1. **Colors**: Edit CSS variables in `:root` selector
2. **Content**: Edit text in `index.html`
3. **Images**: Replace images in `/images` folder
4. **Fonts**: Update Google Fonts link in HTML

### 🛠️ Technologies
- HTML5
- CSS3 (Flexbox, Grid, Custom Properties)
- Vanilla JavaScript (ES6+)

### 📧 Support
For issues or questions, visit: https://github.com/kimigpt

---
Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

    def _generate_deployment_guide(self) -> str:
        """Generate deployment guide"""
        return """# Deployment Guide

## Quick Deployment Options

### 1. Netlify (Recommended - Free)
1. Go to https://app.netlify.com/drop
2. Drag and drop your website folder
3. Your site is live in seconds!
4. Custom domain available

### 2. Vercel (Free)
1. Install Vercel CLI: `npm i -g vercel`
2. Run: `vercel` in your project folder
3. Follow prompts
4. Site deployed!

### 3. GitHub Pages (Free)
1. Create GitHub repository
2. Upload files to repository
3. Go to Settings > Pages
4. Select main branch
5. Save and wait for deployment

### 4. FTP Upload (Traditional)
1. Get FTP credentials from your hosting provider
2. Use FileZilla or similar FTP client
3. Upload all files to public_html or www folder
4. Access via your domain

### 5. Shared Hosting
Upload files via:
- cPanel File Manager
- FTP client
- SSH/SFTP

## Custom Domain Setup

### Netlify
1. Go to Domain Settings
2. Add custom domain
3. Update DNS records at your registrar:
   - Type: A
   - Name: @
   - Value: (Netlify IP)

### Cloudflare (Free SSL)
1. Add site to Cloudflare
2. Update nameservers
3. Enable SSL (Full)

## SSL Certificate
Most platforms provide free SSL automatically via Let's Encrypt.

## Performance Optimization
- Enable Gzip compression
- Set cache headers
- Minify HTML/CSS/JS (if not already done)
- Use CDN for assets

## Troubleshooting
- **404 Errors**: Check file paths are relative
- **Images not loading**: Verify image paths
- **CSS not loading**: Check CSS file path in HTML

---
Happy Deploying! 🚀
"""

    def _create_zip(self, project_name: str, files: Dict[str, str]) -> str:
        """Create ZIP file"""
        # For now, return path - actual ZIP creation happens in preview server
        zip_path = f"generated_sites/{project_name}.zip"
        return zip_path

    def _get_deployment_options(self) -> list:
        """Get available deployment options"""
        return [
            {
                "name": "Download ZIP",
                "description": "Download complete website package",
                "difficulty": "Easy",
                "cost": "Free"
            },
            {
                "name": "Netlify",
                "description": "One-click deploy to Netlify",
                "difficulty": "Easy",
                "cost": "Free"
            },
            {
                "name": "Vercel",
                "description": "Deploy to Vercel platform",
                "difficulty": "Easy",
                "cost": "Free"
            },
            {
                "name": "GitHub Pages",
                "description": "Host on GitHub Pages",
                "difficulty": "Medium",
                "cost": "Free"
            },
            {
                "name": "FTP Upload",
                "description": "Upload via FTP to your server",
                "difficulty": "Medium",
                "cost": "Hosting required"
            }
        ]
